let g:ale_linters['javascript']      = ['deno']
let g:ale_linters['javascriptreact'] = ['deno']
let g:ale_linters['typescriptreact'] = ['deno']
let g:ale_linters['typescript']      = ['deno']
let g:ale_linters['json']            = ['deno']

let g:ale_fixers['javascript']       = ['deno']
let g:ale_fixers['json']             = ['deno']
let g:ale_fixers['typescript']       = ['deno']
let g:ale_fixers['typescriptreact']  = ['deno']
let g:ale_fixers['javascriptreact']  = ['deno']
